name: phungdinhdung
favicon: null
layout_spectrum: 0.07966425968334079
typography_spectrum: 0.47459764732047915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.28049725689925253
  lightness: 0.4723946684971452
  saturation: 0.9070375270675868
  rhythmicContrast: 0.25797066022641957
purpose: []
